version: '3'
services:
  spire-server-frontend:
    build:
      context: ./spire-server
      args:
        - CONFIG_FILE=server1.conf
    hostname: spire-server-frontend
    container_name: spire-server-frontend
    tty: true
  spire-server-backend:
    build:
      context: ./spire-server
      args:
        - CONFIG_FILE=server2.conf
    hostname: spire-server-backend
    container_name: spire-server-backend
    tty: true
  db:
    build: ./database
    hostname: db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./back-end
    hostname: back-end
    tty: true
  frontend:
    build: ./front-end
    tty: true
    depends_on:
      - spire-server-backend
    ports:
    - 9000:9000

